name: "Options Wheel Tracker"
description: "A comprehensive tracker for Options Wheel Strategy and Long stock positions."
version: "1.3.30"
slug: "options_wheel_tracker"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  3001/tcp: 3001
webui: http://[HOST]:[PORT:3001]/
panel_icon: mdi:chart-line
panel_title: "Wheel Tracker"
map:
  - share:rw
options:
  massive_api_key: ""
schema:
  massive_api_key: str?
environment:
  DB_PATH: "/share/wheel_tracker.db"
